name: List Files in Submodule

# Trigger the action on the 'sub-add' branch only
on:
  pull_request:
    branches:
      - main  # Runs when there is a push to the 'sub-add' branch
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4hours

jobs:
  list-files-in-submodule:
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Initialize submodule
        run: |
          git submodule update --init --recursive  # Initialize and update the submodule

      - name: List files in the submodule
        run: |
          tree  # List the contents inside the submodule
          ./newver-checker  # Navigate into the submodule directory
