name: List Files in Submodule

# Trigger the action on the 'sub-add' branch only
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '*/2 * * * *'  # Runs every 4hours

jobs:
  list-files-in-submodule:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out the repository code
        with:
          submodules: 'true'

      - name: Set up Python
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.13'  # Specify Python version
      - run: pip install nvchecker

      - name: Install nvchecker
        run: |
          python -m pip install --upgrade pip
          pip install nvchecker  # Install nvchecker

      - name: Initialize submodule
        run: |
          git submodule update --init --recursive  # Initialize and update the submodule

      - name: List files in the submodule
        run: |
          tree  # List the contents inside the submodule
          chmod +x ./newver-checker  # Give execute permissions to the script

      - name: Run newver-checker
        run: |
          ./newver-checker  # Execute the tool to check for version changes

      - name: Create report file
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Add report file
          signoff: true
          sign-commits: true
          branch-suffix: 'random'
          delete-branch: true
          # labels: report, automated pr
          assignees: bupd
          reviewers: bupd
